### ISSUE TITLE
Support for Pixi v8.x

### ISSUE THREAD

**Issue by phamtrantriem** [lukasz-okuniewicz/custom-pixi-particles#5]
Dear,
Firstly, I'm glad to find out this lib for creating particle with Pixi. Thanks for your works.
At the first view, this looks more adjustment than Pixi Particle-emitter. I'm not relative with js and I dont have enough time to test both so I just confuse does it support for Pixi v8? I see in your readme that the lastest commented information is Pixi v7.

**Comment by lukasz-okuniewicz** [comment]
Hi @phamtrantriem,
I’ve just added support for PixiJS v8.
