### ISSUE TITLE
Pixi 7 Compatibility

### ISSUE THREAD

**Issue by Invisify** [lukasz-okuniewicz/custom-pixi-particles#7]
Hi, it seems that the latest version is not compatible with pixijs 7. Is this intended because the docs mentioned it's supposed to be

**Comment by lukasz-okuniewicz** [comment]
Hi, unfortunately, the latest version (4.16.0) is not compatible with Pixi.js v7. Only the older version (5.2.0), which is no longer maintained, currently works. However, I plan to implement support for the latest Pixi.js versions in the near future.

**Comment by lukasz-okuniewicz** [comment]
Hi @Invisify. I just added support for pixijs v7 and v8.
